version: "3"
services:
  redis:
    image: redis:6.2.4-alpine3.13
    restart: unless-stopped
    command: redis-server --appendonly yes
    volumes:
      - "$PWD/redis_data:/data"
  ip:
    hostname: ip
    build: .
    image: jrcichra/ip
    restart: unless-stopped
    ports:
      - 8888:8080
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/"]
      interval: 30s
      timeout: 20s
      retries: 3
